In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

Transition matrix

In [35]:
T = np.array([[0.99, 0.8], [0.01, 0.2]])
T

array([[0.99, 0.8 ],
       [0.01, 0.2 ]])

Eigenvalues and eigenvectors

In [59]:
l, v = np.linalg.eig(T)

Eigenvalues:

In [60]:
l

array([ 1.       , -0.0067035,  0.5967035])

Eigenvectors

In [61]:
v

array([[ 0.99991876, -0.61866785, -0.81645836],
       [ 0.01249898,  0.77078551,  0.40138777],
       [ 0.0024998 , -0.15211766,  0.41507059]])

In [62]:
v0 = v[:,0]
v0

array([0.99991876, 0.01249898, 0.0024998 ])

In [63]:
v1 = v[:,1]
v1

array([-0.61866785,  0.77078551, -0.15211766])

In [56]:
T.dot(v0)

array([0.99992188, 0.01249902, 0.        ])

In [57]:
T.dot(v1)

array([-0.13435029,  0.13435029,  0.        ])

$T^{n}$

In [44]:
np.linalg.matrix_power(A, 1000)

array([[0.98765432, 0.98765432],
       [0.01234568, 0.01234568]])

In [45]:
v0 = np.array([[1], [0]])
v0

array([[1],
       [0]])

In [58]:
#T = np.array([[0.99, 0.8, 0.0], [0.01, 0.1,0.5], [0.0, 0.1, 0.5]])
#T

array([[0.99, 0.8 , 0.  ],
       [0.01, 0.1 , 0.5 ],
       [0.  , 0.1 , 0.5 ]])